export const talentNodes = [
  {
    id: "root",
    title: "Diff's Talent Tree",
    tier: "Root Node",
    subtitle: "Start here and unlock each branch",
    skills: [],
    className: "talent-pos-root",
  },
  {
    id: "languages",
    title: "Languages",
    tier: "Layer 1",
    skills: [
      { name: "C++", logo: "/assets/logos/cplusplus.svg", short: "C++" },
      { name: "Java", logo: "/assets/logos/java.png", short: "Java" },
      { name: "Python", logo: "/assets/logos/python.png", short: "Py" },
      { name: "JavaScript", logo: "/assets/logos/javascript.svg", short: "JS" },
      { name: "TypeScript", logo: "/assets/logos/icons8-typescript.svg", short: "TS" },
      { name: "C#", logo: "/assets/logos/csharp.svg", short: "C#" },
    ],
    className: "talent-pos-languages",
  },
  {
    id: "frontend",
    title: "Front-end",
    tier: "Layer 2",
    skills: [
      { name: "React", logo: "/assets/logos/react.svg", short: "React" },
      { name: "Vue", logo: "/assets/logos/icons8-vue-js.svg", short: "Vue" },
      { name: "Next.js", logo: "/assets/logos/icons8-nextjs.svg", short: "Next" },
      { name: "Tailwind CSS", logo: "/assets/logos/tailwindcss.svg", short: "TW" },
      { name: "Nuxt 3", logo: "/assets/logos/icons8-nuxt-js.svg", short: "Nuxt" },
    ],
    className: "talent-pos-frontend",
  },
  {
    id: "backend",
    title: "Back-end",
    tier: "Layer 2",
    skills: [
      { name: "Spring Boot", logo: "/assets/logos/springboot.png", short: "Spring" },
      { name: "NestJS", logo: "/assets/logos/icons8-nestjs.svg", short: "Nest" },
      { name: "Node.js", logo: "/assets/logos/icons8-nodejs-50.svg", short: "Node" },
      { name: "PHP", logo: "/assets/logos/icons8-php-48.png", short: "PHP" },
      { name: "Django", logo: "/assets/logos/django.png", short: "Django" },
      { name: "Flask", logo: "/assets/logos/python.png", short: "Flask" },
    ],
    className: "talent-pos-backend",
  },
  {
    id: "databases",
    title: "Databases",
    tier: "Layer 3",
    skills: [
      { name: "Firebase", logo: "/assets/logos/icons8-firebase.svg", short: "FB" },
      { name: "PostgreSQL", logo: "/assets/logos/postgre.png", short: "PG" },
      { name: "MySQL", logo: "/assets/logos/mysql.png", short: "MySQL" },
      { name: "MongoDB", logo: "/assets/logos/icons8-mongo-db-32.png", short: "MDB" },
      { name: "Prisma", logo: "/assets/logos/icons8-prisma-orm-50.svg", short: "Prisma" },
      { name: "Drizzle ORM", logo: "/assets/logos/drizzle.svg", short: "Drizzle" },
    ],
    className: "talent-pos-databases",
  },
  {
    id: "tools",
    title: "Tools",
    tier: "Layer 3",
    skills: [
      { name: "Docker", logo: "/assets/logos/icons8-docker.svg", short: "Docker" },
      { name: "DBeaver", logo: "/assets/logos/icons8-dbeaver-64.png", short: "DB" },
      { name: "Postman", logo: "/assets/logos/icons8-postman-api-48.png", short: "Postman" },
      { name: "Git", logo: "/assets/logos/git.svg", short: "Git" },
      { name: "GitHub", logo: "/assets/logos/github.svg", short: "GH" },
      { name: "TurboRepo", logo: "/assets/logos/turbo repo.png", short: "Turbo" },
      { name: "Stripe", logo: "/assets/logos/stripe.svg", short: "Stripe" },
    ],
    className: "talent-pos-tools",
  },
  {
    id: "exploring",
    title: "Exploring",
    tier: "Passive Talent",
    skills: [
      { name: "AWS", logo: "/assets/logos/aws-svgrepo-com.svg", short: "AWS" },
      {
        name: "Kubernetes",
        logo: "/assets/logos/kubernetes-svgrepo-com.svg",
        short: "K8s",
      },
      { name: "Auth0", logo: "/assets/logos/auth0.svg", short: "Auth0" },
      { name: "Three.js", logo: "/assets/logos/threejs.svg", short: "3JS" },
      { name: "OpenAI API", logo: "", short: "AI" },
    ],
    className: "talent-pos-exploring",
    sideQuest: true,
  },
];

export const treeEdges = [
  { from: "root", to: "languages" },
  { from: "languages", to: "frontend" },
  { from: "languages", to: "backend" },
  { from: "frontend", to: "databases" },
  { from: "backend", to: "databases" },
  { from: "backend", to: "tools" },
  {
    from: "languages",
    to: "exploring",
    variant: "sidequest",
    fromAnchor: "right",
    toAnchor: "left",
  },
];
